In [176]:
import pandas as pd
import numpy as np
a=pd.read_csv("iris.csv")

In [177]:
a.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [178]:
a.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [179]:
a.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [180]:
x=a.iloc[:,0:4]

In [181]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [182]:
y=a.iloc[:,4:5]

In [183]:
y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [184]:
a['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [185]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [186]:
y1=ColumnTransformer(
    transformers=[
        ('tr1',(OrdinalEncoder(categories=[['setosa','versicolor','virginica']])),['species'])
    ])

In [187]:
y1

ColumnTransformer(transformers=[('tr1',
                                 OrdinalEncoder(categories=[['setosa',
                                                             'versicolor',
                                                             'virginica']]),
                                 ['species'])])

In [188]:
y1=y1.fit_transform(y)
y1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [189]:
from sklearn.model_selection import train_test_split

In [190]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y1,random_state=2,train_size=0.8)

In [191]:
xtrain

sepal_length  sepal_width  petal_length  petal_width
126           6.2          2.8           4.8          1.8
23            5.1          3.3           1.7          0.5
64            5.6          2.9           3.6          1.3
117           7.7          3.8           6.7          2.2
84            5.4          3.0           4.5          1.5
..            ...          ...           ...          ...
75            6.6          3.0           4.4          1.4
43            5.0          3.5           1.6          0.6
22            4.6          3.6           1.0          0.2
72            6.3          2.5           4.9          1.5
15            5.7          4.4           1.5          0.4

[120 rows x 4 columns]

In [192]:
ytrain

array([[2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [2.],
       [0.],
       [0.],

In [193]:
xtest

sepal_length  sepal_width  petal_length  petal_width
6             4.6          3.4           1.4          0.3
3             4.6          3.1           1.5          0.2
113           5.7          2.5           5.0          2.0
12            4.8          3.0           1.4          0.1
24            4.8          3.4           1.9          0.2
129           7.2          3.0           5.8          1.6
25            5.0          3.0           1.6          0.2
108           6.7          2.5           5.8          1.8
128           6.4          2.8           5.6          2.1
45            4.8          3.0           1.4          0.3
48            5.3          3.7           1.5          0.2
42            4.4          3.2           1.3          0.2
35            5.0          3.2           1.2          0.2
5             5.4          3.9           1.7          0.4
85            6.0          3.4           4.5          1.6
54            6.5          2.8           4.6          1.5
41            4.5          2.3           1.3          0.3
96            5.7          2.9           4.2          1.3
144           6.7          3.3           5.7          2.5
89            5.5          2.5           4.0          1.3
77            6.7          3.0           5.0          1.7
74            6.4          2.9           4.3          1.3
115           6.4          3.2           5.3          2.3
94            5.6          2.7           4.2          1.3
87            6.3          2.3           4.4          1.3
29            4.7          3.2           1.6          0.2
2             4.7          3.2           1.3          0.2
127           6.1          3.0           4.9          1.8
44            5.1          3.8           1.9          0.4
125           7.2          3.2           6.0          1.8

In [194]:
ytest

array([[0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.]])

In [195]:
from sklearn.tree import DecisionTreeClassifier

In [196]:
new=DecisionTreeClassifier()

In [197]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [198]:
pred=new.predict(xtest)

In [199]:
pred

array([0., 0., 2., 0., 0., 1., 0., 2., 2., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 2., 1., 2., 1., 2., 1., 1., 0., 0., 2., 0., 2.])

In [200]:
ytest

array([[0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.]])

In [201]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score

In [202]:
confusion_matrix(ytest,pred)

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  1,  7]], dtype=int64)

In [203]:
accuracy_score(ytest,pred)

0.9333333333333333

In [204]:
recall_score(ytest,pred,    average='micro')

0.9333333333333333

In [205]:
from sklearn.tree import DecisionTreeClassifier

In [208]:
new=DecisionTreeClassifier(criterion='entropy',splitter='random',max_depth=5)

In [209]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=5, splitter='random')

In [210]:
pred=new.predict(xtest)

In [211]:
pred

array([0., 0., 2., 0., 0., 2., 0., 2., 2., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 2., 1., 2., 1., 2., 1., 1., 0., 0., 2., 0., 2.])

In [212]:
ytest

array([[0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.]])

In [213]:
accuracy_score(ytest,pred)

0.9666666666666667

In [218]:
confusion_matrix(ytest,pred)

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  0,  8]], dtype=int64)

In [223]:
recall_score(ytest,pred,average='micro')

0.9666666666666667