In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv("dataset/covid.csv")

In [3]:
a.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
a.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
a.describe()

age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [6]:
a.shape

(100, 6)

In [7]:
a['cough'].unique()

array(['Mild', 'Strong'], dtype=object)

# Aam Zindagi

In [8]:
from sklearn.impute import SimpleImputer

# Mentos Zindagi

# WIHOUT USING SKTLEARN

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [10]:
tr=ColumnTransformer(
        transformers=[
            ('tr1',OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
            ('tr2',OneHotEncoder(drop='first',sparse=False),['gender','city']),
            ('tr3',SimpleImputer(),['fever'])
        ],remainder='passthrough')

In [11]:
tr.fit_transform(a)

array([[0.0, 1.0, 0.0, 1.0, 0.0, 103.0, 60, 'No'],
       [0.0, 1.0, 1.0, 0.0, 0.0, 100.0, 27, 'Yes'],
       [0.0, 1.0, 1.0, 0.0, 0.0, 101.0, 42, 'No'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 98.0, 31, 'No'],
       [0.0, 0.0, 0.0, 0.0, 1.0, 101.0, 65, 'No'],
       [0.0, 0.0, 0.0, 0.0, 0.0, 100.84444444444445, 84, 'Yes'],
       [1.0, 1.0, 0.0, 0.0, 0.0, 101.0, 14, 'No'],
       [1.0, 0.0, 0.0, 0.0, 1.0, 100.84444444444445, 20, 'Yes'],
       [1.0, 0.0, 0.0, 0.0, 0.0, 100.0, 19, 'No'],
       [0.0, 0.0, 1.0, 0.0, 0.0, 101.0, 64, 'No'],
       [0.0, 0.0, 1.0, 0.0, 0.0, 100.84444444444445, 75, 'No'],
       [0.0, 0.0, 0.0, 0.0, 1.0, 98.0, 65, 'Yes'],
       [1.0, 0.0, 0.0, 1.0, 0.0, 99.0, 25, 'No'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 102.0, 64, 'Yes'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 104.0, 51, 'No'],
       [1.0, 1.0, 0.0, 1.0, 0.0, 103.0, 70, 'Yes'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 103.0, 69, 'Yes'],
       [1.0, 0.0, 1.0, 0.0, 0.0, 98.0, 40, 'No'],
       [0.0, 0.0, 0.0, 0.0, 0.0, 98.0, 6

# Using split function

In [12]:
x=a.iloc[:,0:5]

In [13]:
x

age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [14]:
y=a.iloc[:,5:]

In [15]:
y

has_covid
0         No
1        Yes
2         No
3         No
4         No
..       ...
95        No
96       Yes
97        No
98        No
99       Yes

[100 rows x 1 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=2,test_size=1/3)

In [18]:
xtrain

age  gender  fever   cough       city
36   38  Female  101.0    Mild  Bangalore
78   11    Male  100.0    Mild  Bangalore
6    14    Male  101.0  Strong  Bangalore
89   46    Male  103.0  Strong  Bangalore
91   38    Male    NaN    Mild      Delhi
..  ...     ...    ...     ...        ...
43   22  Female   99.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
72   83  Female  101.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi

[66 rows x 5 columns]

In [19]:
ytrain

has_covid
36        No
78       Yes
6         No
89        No
91       Yes
..       ...
43       Yes
22       Yes
72        No
15       Yes
40        No

[66 rows x 1 columns]

In [20]:
xtest.head()

age  gender  fever   cough     city
83   17  Female  104.0    Mild  Kolkata
30   15    Male  101.0    Mild    Delhi
56   71    Male    NaN  Strong  Kolkata
24   13  Female  100.0  Strong  Kolkata
16   69  Female  103.0    Mild  Kolkata

In [21]:
ytest.head()

has_covid
83        No
30       Yes
56        No
24        No
16       Yes

In [22]:
from sklearn.compose import ColumnTransformer

In [23]:
tr=ColumnTransformer(
        transformers=[
            ('tr1',OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
            ('tr2',OneHotEncoder(drop='first',sparse=False),['gender','city']),
            ('tr3',SimpleImputer(),['fever'])
        ],remainder='passthrough')

In [24]:
xtrain=tr.fit_transform(xtrain)

In [25]:
xtest=tr.fit_transform(xtest)

In [26]:
tr=ColumnTransformer(
        transformers=[
            ('tr1',OneHotEncoder(drop='first',sparse=False),['has_covid'])],
    remainder='passthrough')

In [27]:
ytrain=tr.fit_transform(ytrain)

In [28]:
ytest=tr.fit_transform(ytest)

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [30]:
new=DecisionTreeClassifier()

In [31]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [32]:
pred=new.predict(xtest)

In [33]:
pred

array([0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0.])

In [35]:
ytest

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]])