In [181]:
import numpy as np
import pandas as pd

In [182]:
a=pd.read_csv("dataset/titanic.csv")

In [183]:
a.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [184]:
a=a.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [185]:
a.isnull().sum()


Survived      4
Pclass        0
Sex           0
Age         178
SibSp         0
Parch         0
Fare          3
Embarked      2
dtype: int64

In [186]:
a=a.dropna(subset=['Survived','Fare','Embarked'])

In [187]:
a.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         175
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [188]:
x=a.iloc[:,1:]

In [189]:
x

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
4         3    male  35.0      0      0   8.0500        S
5         3    male   NaN      0      0   8.4583        Q
6         1    male  54.0      0      0  51.8625        S
7         3    male   2.0      3      1  21.0750        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[883 rows x 7 columns]

In [190]:
y=a.iloc[:,:1]

In [191]:
y

Survived
0         0.0
4         0.0
5         0.0
6         0.0
7         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[883 rows x 1 columns]

In [192]:
from sklearn.model_selection import train_test_split

In [193]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=1/3)

In [194]:
xtrain

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
172       3  female   1.0      1      1   11.1333        S
199       2  female  24.0      0      0   13.0000        S
459       3    male   NaN      0      0    7.7500        Q
674       2    male   NaN      0      0    0.0000        S
337       1  female  41.0      0      0  134.5000        C
..      ...     ...   ...    ...    ...       ...      ...
840       3    male  20.0      0      0    7.9250        S
384       3    male   NaN      0      0    7.8958        S
358       3  female   NaN      0      0    7.8792        Q
535       2  female   7.0      0      2   26.2500        S
111       3  female  14.5      1      0   14.4542        C

[588 rows x 7 columns]

In [195]:
xtest

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
562       2    male  28.0      0      0  13.5000        S
420       3    male   NaN      0      0   7.8958        C
304       3    male   NaN      0      0   8.0500        S
255       3  female  29.0      0      2  15.2458        C
502       3  female   NaN      0      0   7.6292        Q
..      ...     ...   ...    ...    ...      ...      ...
883       2    male  28.0      0      0  10.5000        S
171       3    male   4.0      4      1  29.1250        Q
192       3  female  19.0      1      0   7.8542        S
762       3    male  20.0      0      0   7.2292        C
36        3    male   NaN      0      0   7.2292        C

[295 rows x 7 columns]

In [196]:
ytrain

Survived
172       1.0
199       0.0
459       0.0
674       0.0
337       1.0
..        ...
840       0.0
384       0.0
358       1.0
535       1.0
111       0.0

[588 rows x 1 columns]

In [197]:
ytest

Survived
562       0.0
420       0.0
304       0.0
255       1.0
502       0.0
..        ...
883       0.0
171       0.0
192       1.0
762       1.0
36        1.0

[295 rows x 1 columns]

In [198]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [199]:
tr=ColumnTransformer(
    transformers=(
    ('tr1',OrdinalEncoder(categories=[[1,2,3]]),['Pclass']),
    ('tr2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked']),
    ('tr3',SimpleImputer(),['Age']))
)

In [200]:
tr

ColumnTransformer(transformers=(('tr1', OrdinalEncoder(categories=[[1, 2, 3]]),
                                 ['Pclass']),
                                ('tr2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Sex', 'Embarked']),
                                ('tr3', SimpleImputer(), ['Age'])))

In [201]:
tr.fit_transform(xtrain)

array([[ 2.        ,  0.        ,  0.        ,  1.        ,  1.        ],
       [ 1.        ,  0.        ,  0.        ,  1.        , 24.        ],
       [ 2.        ,  1.        ,  1.        ,  0.        , 30.38674322],
       ...,
       [ 2.        ,  0.        ,  1.        ,  0.        , 30.38674322],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  7.        ],
       [ 2.        ,  0.        ,  0.        ,  0.        , 14.5       ]])

In [202]:
tr.fit_transform(xtest)

array([[ 1.        ,  1.        ,  0.        ,  1.        , 28.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        , 28.11755459],
       [ 2.        ,  1.        ,  0.        ,  1.        , 28.11755459],
       ...,
       [ 2.        ,  0.        ,  0.        ,  1.        , 19.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        , 20.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        , 28.11755459]])

In [203]:
b=tr.fit_transform(a)
b

array([[ 2.        ,  1.        ,  0.        ,  1.        , 22.        ],
       [ 2.        ,  1.        ,  0.        ,  1.        , 35.        ],
       [ 2.        ,  1.        ,  1.        ,  0.        , 29.65278249],
       ...,
       [ 2.        ,  0.        ,  0.        ,  1.        , 29.65278249],
       [ 0.        ,  1.        ,  0.        ,  0.        , 26.        ],
       [ 2.        ,  1.        ,  1.        ,  0.        , 32.        ]])

In [204]:
c=pd.DataFrame(b)

In [205]:
c

0    1    2    3          4
0    2.0  1.0  0.0  1.0  22.000000
1    2.0  1.0  0.0  1.0  35.000000
2    2.0  1.0  1.0  0.0  29.652782
3    0.0  1.0  0.0  1.0  54.000000
4    2.0  1.0  0.0  1.0   2.000000
..   ...  ...  ...  ...        ...
878  1.0  1.0  0.0  1.0  27.000000
879  0.0  0.0  0.0  1.0  19.000000
880  2.0  0.0  0.0  1.0  29.652782
881  0.0  1.0  0.0  0.0  26.000000
882  2.0  1.0  1.0  0.0  32.000000

[883 rows x 5 columns]