In [618]:
import pandas as pd
import numpy as np
a=pd.read_csv("dataset/Housing.csv")

In [619]:
a

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [620]:
x=a.drop(columns="furnishingstatus")

In [621]:
a

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [622]:
y=a.iloc[:,-1:]

In [623]:
y

furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
..               ...
540      unfurnished
541   semi-furnished
542      unfurnished
543        furnished
544      unfurnished

[545 rows x 1 columns]

In [624]:
x1=pd.get_dummies(x,drop_first=True)

In [625]:
x1

price  area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
0    13300000  7420         4          2        3        2             1   
1    12250000  8960         4          4        4        3             1   
2    12250000  9960         3          2        2        2             1   
3    12215000  7500         4          2        2        3             1   
4    11410000  7420         4          1        2        2             1   
..        ...   ...       ...        ...      ...      ...           ...   
540   1820000  3000         2          1        1        2             1   
541   1767150  2400         3          1        1        0             0   
542   1750000  3620         2          1        1        0             1   
543   1750000  2910         3          1        1        0             0   
544   1750000  3850         3          1        2        0             1   

     guestroom_yes  basement_yes  hotwaterheating_yes  airconditioning_yes  \
0                0             0                    0                    1   
1                0             0                    0                    1   
2                0             1                    0                    0   
3                0             1                    0                    1   
4                1             1                    0                    1   
..             ...           ...                  ...                  ...   
540              0             1                    0                    0   
541              0             0                    0                    0   
542              0             0                    0                    0   
543              0             0                    0                    0   
544              0             0                    0                    0   

     prefarea_yes  
0               1  
1               0  
2               1  
3               1  
4               0  
..            ...  
540             0  
541             0  
542             0  
543             0  
544             0  

[545 rows x 12 columns]

In [626]:
from sklearn.preprocessing import LabelEncoder

In [627]:
new=LabelEncoder()

In [628]:
y=new.fit_transform(y)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [629]:
from sklearn.model_selection import train_test_split

In [630]:
xtrain,xtest,ytrain,ytest=train_test_split(x1,y,random_state=0,test_size=0.2)

In [631]:
xtrain

price   area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
542  1750000   3620         2          1        1        0             1   
496  2695000   4000         2          1        1        0             1   
484  2870000   3040         2          1        1        0             0   
507  2590000   3600         2          1        1        0             1   
252  4515000   9860         3          1        1        0             1   
..       ...    ...       ...        ...      ...      ...           ...   
70   6790000   4000         3          2        2        0             1   
277  4305000  10360         2          1        1        1             1   
9    9800000   5750         3          2        4        1             1   
359  3710000   3600         3          1        1        1             1   
192  5040000   6600         3          1        1        0             1   

     guestroom_yes  basement_yes  hotwaterheating_yes  airconditioning_yes  \
542              0             0                    0                    0   
496              0             0                    0                    0   
484              0             0                    0                    0   
507              0             0                    0                    0   
252              0             0                    0                    0   
..             ...           ...                  ...                  ...   
70               0             1                    0                    1   
277              0             0                    0                    0   
9                1             0                    0                    1   
359              0             0                    0                    0   
192              1             1                    0                    0   

     prefarea_yes  
542             0  
496             0  
484             0  
507             0  
252             0  
..            ...  
70              1  
277             1  
9               1  
359             0  
192             1  

[436 rows x 12 columns]

In [632]:
ytrain

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 1,
       0, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 0, 1, 1, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0,
       0, 2, 2, 2, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1,
       2, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1,
       1, 2, 2, 0, 1, 2, 0, 2, 1, 0, 1, 2, 0, 1, 1, 2, 1, 0, 2, 2, 1, 1,
       0, 1, 2, 1, 1, 2, 1, 2, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 1, 1, 0,
       1, 1, 0, 2, 1, 2, 0, 0, 0, 2, 1, 1, 2, 1, 1, 1, 0, 2, 0, 0, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2, 2, 0, 1,
       2, 2, 0, 1, 0, 1, 1, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0,
       2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0,
       1, 2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2,
       0, 1, 2, 0, 1, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2,
       0, 2, 1, 2, 0, 0, 0, 1, 1, 2, 0, 1, 2, 1, 0,

In [633]:
xtest

price   area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
239  4585000   4000         3          1        2        1             1   
113  6083000   9620         3          1        1        2             1   
325  4007500   3460         4          1        2        0             1   
66   6930000  13200         2          1        1        1             1   
479  2940000   3660         4          1        2        0             0   
..       ...    ...       ...        ...      ...      ...           ...   
76   6650000   6420         3          2        3        0             1   
132  5810000   5200         3          1        3        0             1   
311  4123000   6060         2          1        1        1             1   
464  3080000   4500         2          1        2        1             1   
155  5530000   6100         3          2        1        2             1   

     guestroom_yes  basement_yes  hotwaterheating_yes  airconditioning_yes  \
239              0             0                    0                    0   
113              0             1                    0                    0   
325              0             0                    0                    1   
66               0             1                    1                    0   
479              0             0                    0                    0   
..             ...           ...                  ...                  ...   
76               0             0                    0                    1   
132              0             0                    0                    1   
311              0             1                    0                    0   
464              0             0                    1                    0   
155              0             1                    0                    0   

     prefarea_yes  
239             0  
113             1  
325             0  
66              0  
479             0  
..            ...  
76              1  
132             0  
311             0  
464             0  
155             1  

[109 rows x 12 columns]

In [634]:
ytest

array([0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 1, 0, 2, 0, 2, 2, 2,
       2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0,
       2, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0])

In [635]:
from sklearn.tree import DecisionTreeClassifier

In [636]:
new=DecisionTreeClassifier(criterion='gini',max_depth=None,splitter='best',)

In [637]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [638]:
pre=new.predict(xtest)

In [639]:
pre

array([1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 0, 1, 1, 1,
       1, 2, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2,
       1, 1, 0, 2, 1, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 0, 1, 1,
       0, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 0, 0, 1, 2, 2, 0, 0, 1, 0, 2, 1, 0, 1, 1, 0, 1])

In [640]:
ytest

array([0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 1, 0, 2, 0, 2, 2, 2,
       2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0,
       2, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0])

In [641]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score

In [642]:
accuracy_score(ytest,pre)

0.45871559633027525

In [643]:
confusion_matrix(ytest,pre)

array([[ 8, 15, 11],
       [ 9, 28, 10],
       [ 5,  9, 14]], dtype=int64)

In [644]:
recall_score(ytest,pre,average='micro')

0.45871559633027525

In [645]:
precision_score(ytest,pre,average='micro')

0.45871559633027525

In [646]:
import pandas as pd
import numpy as np

In [647]:
a

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [648]:
a.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [649]:
a['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [650]:
x1=a.iloc[:,1:]

In [651]:
x1

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [652]:
y1=a.iloc[:,-1:]

In [653]:
y1

furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
..               ...
540      unfurnished
541   semi-furnished
542      unfurnished
543        furnished
544      unfurnished

[545 rows x 1 columns]

In [654]:
from sklearn.preprocessing import LabelEncoder

In [655]:
new1=LabelEncoder()

In [656]:
y1=new1.fit_transform(y1)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [657]:
from sklearn.model_selection import train_test_split

In [658]:
xtrain,xtest,ytrain,ytest=train_test_split(x1,y1,train_size=0.2,random_state=2)

In [659]:
xtrain

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
512  3000         2          1        2      yes        no       no   
509  3600         2          2        2      yes        no      yes   
484  3040         2          1        1       no        no       no   
158  7980         3          1        1      yes        no       no   
143  4800         5          2        3       no        no      yes   
..    ...       ...        ...      ...      ...       ...      ...   
299  7000         3          1        1      yes        no       no   
534  3000         4          1        2      yes        no       no   
493  3960         3          1        1      yes        no       no   
527  1836         2          1        1       no        no      yes   
168  4260         4          1        2      yes        no      yes   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
512              no              no        0       no        furnished  
509              no              no        1       no        furnished  
484              no              no        0       no      unfurnished  
158              no              no        2       no   semi-furnished  
143             yes              no        0       no      unfurnished  
..              ...             ...      ...      ...              ...  
299              no              no        3       no        furnished  
534              no              no        0       no      unfurnished  
493              no              no        0       no        furnished  
527              no              no        0       no   semi-furnished  
168              no             yes        0       no        furnished  

[109 rows x 12 columns]

In [660]:
ytrain

array([0, 0, 2, 1, 2, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 1, 0, 1, 2, 0, 0, 1, 2, 2, 2, 1,
       2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2,
       1, 1, 2, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0])

In [661]:
xtest

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
333  3000         3          1        2      yes        no       no   
84   3760         3          1        2      yes        no       no   
439  3930         2          1        1       no        no       no   
396  3640         2          1        1      yes        no       no   
161  6100         3          1        3      yes       yes       no   
..    ...       ...        ...      ...      ...       ...      ...   
177  6050         3          1        1      yes        no      yes   
187  6100         3          1        1      yes        no      yes   
458  3850         3          1        2      yes        no       no   
148  6360         3          1        3      yes        no       no   
239  4000         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
333              no              no        0       no   semi-furnished  
84              yes              no        2       no   semi-furnished  
439              no              no        0       no      unfurnished  
396              no              no        1       no   semi-furnished  
161              no             yes        0      yes   semi-furnished  
..              ...             ...      ...      ...              ...  
177              no              no        0      yes   semi-furnished  
187              no             yes        0      yes   semi-furnished  
458              no              no        0       no      unfurnished  
148              no              no        0      yes   semi-furnished  
239              no              no        1       no        furnished  

[436 rows x 12 columns]

In [662]:
ytest

array([1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 1, 2, 1, 1, 2,
       1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 1,
       2, 1, 2, 2, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 0,
       1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 0, 2,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 2, 2, 1, 2, 1, 0, 1, 1, 2,
       0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 1, 2, 1,
       2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0,
       2, 0, 1, 1, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0,
       0, 1, 2, 0, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 0, 1,
       1, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2,
       1, 2, 2, 1, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 2, 2, 2,
       2, 1, 2, 0, 2, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 2, 2, 0,
       2, 1, 2, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1,

In [663]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
tr=ColumnTransformer(
transformers=[
    ('tr1',OneHotEncoder(drop='first',sparse=True),['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']),
    ('tr2',OrdinalEncoder(categories=[['furnished', 'semi-furnished', 'unfurnished']]),['furnishingstatus'])
],remainder='passthrough')

In [664]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1', OneHotEncoder(drop='first'),
                                 ['mainroad', 'guestroom', 'basement',
                                  'hotwaterheating', 'airconditioning',
                                  'prefarea']),
                                ('tr2',
                                 OrdinalEncoder(categories=[['furnished',
                                                             'semi-furnished',
                                                             'unfurnished']]),
                                 ['furnishingstatus'])])

In [665]:
xtrain = tr.fit_transform(xtrain)
xtrain


array([[1., 0., 0., ..., 1., 2., 0.],
       [1., 0., 1., ..., 2., 2., 1.],
       [0., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 0., 1., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 2., 0.]])

In [666]:
xtest=tr.fit_transform(xtest)

In [667]:
xtest

array([[1., 0., 0., ..., 1., 2., 0.],
       [1., 0., 0., ..., 1., 2., 2.],
       [0., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 2., 0.],
       [1., 0., 0., ..., 1., 3., 0.],
       [1., 0., 0., ..., 1., 2., 1.]])

In [668]:
from sklearn.linear_model import LinearRegression

In [669]:
new=LinearRegression()

In [670]:
new.fit(xtrain,ytrain)

LinearRegression()

In [671]:
pre=new.predict(xtest)

In [672]:
pre

array([ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  2.00000000e+00,  2.00000000e+00,
       -5.27124874e-15,  2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
        2.00000000e+00,  2.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        4.39295864e-15,  1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  2.00000000e+00,  1.00000000e+00,  3.01625023e-15,
        2.00000000e+00, -6.69655381e-15,  2.00000000e+00, -3.47474657e-15,
        2.00000000e+00, -7.61758541e-15, -3.36283396e-15, -6.61193621e-15,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.15161419e-14,
        2.00000000e+00,  2.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        1.00000000e+00,  2.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        2.00000000e+00,  1.00000000e+00,  2.00000000e+00,  2.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.09310670e-14,  1.00000000e+00,
        2.00000000e+00,  

In [673]:
ytest

array([1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 1, 2, 1, 1, 2,
       1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 1,
       2, 1, 2, 2, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 0,
       1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 0, 2,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 2, 2, 1, 2, 1, 0, 1, 1, 2,
       0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 1, 2, 1,
       2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0,
       2, 0, 1, 1, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0,
       0, 1, 2, 0, 1, 2, 1, 1, 0, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 0, 1,
       1, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2,
       1, 2, 2, 1, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 2, 2, 2,
       2, 1, 2, 0, 2, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 2, 2, 0,
       2, 1, 2, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1,

In [674]:
from sklearn.metrics import r2_score
r2_score(ytest,pre)

1.0

In [675]:
from sklearn.metrics import mean_absolute_error

In [678]:
mean_absolute_error(ytest,pre)

5.0584628941644236e-15