# Numpy accessing the element using 1D Array

In [8]:
import numpy as np
a=np.array([2,4,3,5,6])
a

array([2, 4, 3, 5, 6])

In [22]:
a[0]

2

In [9]:
a[1]

4

In [10]:
a[3]

5

# slicing the 1D Array

In [19]:
import numpy as np
a=np.array([2,4,3,5,6])
a

array([2, 4, 3, 5, 6])

In [20]:
a[0:3]

array([2, 4, 3])

# Accessing the 2D Array

In [21]:
import numpy as np
ab=np.array([[2,4,3,5,6],[2,5,4,6,5]])
ab

array([[2, 4, 3, 5, 6],
       [2, 5, 4, 6, 5]])

In [23]:
ab[1]

array([2, 5, 4, 6, 5])

In [26]:
ab[0,1]

4

In [27]:
ab[0,-1]

6

In [29]:
ab[-1,-3]

4

In [30]:
ab[-2,-5]

2

# SLICING THE 2D ARRAY

In [12]:
import numpy as np
ab=np.array([[2,4,3,5,6],[2,5,4,6,5]])
ab

array([[2, 4, 3, 5, 6],
       [2, 5, 4, 6, 5]])

In [31]:
ab[:1]

array([[2, 4, 3, 5, 6]])

In [32]:
ab[0:2,2:5]

array([[3, 5, 6],
       [4, 6, 5]])

In [33]:
ab[0:3,0:3]

array([[2, 4, 3],
       [2, 5, 4]])

In [13]:
ab[0:2]

array([[2, 4, 3, 5, 6],
       [2, 5, 4, 6, 5]])

In [14]:
ab[1:2,2:5]

array([[4, 6, 5]])

In [16]:
ab[1,:3]

array([2, 5, 4])

In [17]:
ab[:,-1]

array([6, 5])

In [18]:
ab[1:3,2:5]

array([[4, 6, 5]])

# find mean and median

In [40]:
a=[150,290,450,234,345]
b=np.array(a)
ans=b.mean()
ans1=np.median(b)
print(b)
print(ans)
print(ans1)

[150 290 450 234 345]
293.8
290.0


# Min Max

In [41]:
a=[150,290,450,234,345]
b=np.array(a)
ans=b.min()
ans1=np.max(b)
print(b)
print(ans)
print(ans1)

[150 290 450 234 345]
150
450


# Argmin and Argmax

In [42]:
a=[150,290,450,234,345]
b=np.array(a)
ans=b.argmin()
ans1=np.argmax(b)
print(b)
print(ans)
print(ans1)

[150 290 450 234 345]
0
2


# Where function

In [47]:
a=np.array([130,150,160,120,190])
print(a)
ans=np.where(a>150)
print(a[ans])

[130 150 160 120 190]
[160 190]


# Filter function

In [ ]:
a=np.array([120,140,150,190,180])
fil=a>150
print(a[fil])
