In [11]:
import numpy as np
a=np.array([3,8,9,6,5])
print(a)
print(a.shape)
print(a.dtype)

[3 8 9 6 5]
(5,)
int32


In [12]:
import numpy as np
a=np.arange(10)
print(a)
print(a.shape)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int32


In [13]:
import numpy as np
a=np.array([3.0,8.6,9.5,6.3,5.7])
print(a)
print(a.shape)
print(a.dtype)

[3.  8.6 9.5 6.3 5.7]
(5,)
float64


In [14]:
import numpy as np
a=np.arange(13.5)
print(a)
print(a.shape)
print(a.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
(14,)
float64


In [15]:
import numpy as np
a=np.array([[2,4,6],[4,6,7]])
print(a)
print(a.shape)
print(a.dtype)

[[2 4 6]
 [4 6 7]]
(2, 3)
int32


In [21]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
print(a.shape)
print(a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
int32


In [18]:
import numpy as np
a=np.array([[3.9,8.8,9.5],[6.8,5.4,8.5]])
print(a)
print(a.shape)
print(a.dtype)

[[3.9 8.8 9.5]
 [6.8 5.4 8.5]]
(2, 3)
float64


In [22]:
import numpy as np
a=np.arange(10.).reshape(2,5)
print(a)
print(a.shape)
print(a.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
(2, 5)
float64
