In [15]:
import numpy as np
a=np.array([1,4,6,8,6])
print(a)
print(a.shape)
print(a.dtype)

[1 4 6 8 6]
(5,)
int32


In [16]:
import numpy as np
a=np.arange(10)
print(a)
print(a.shape)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int32


In [17]:
a=np.array([2.,4.,5.,4.5,7.6])
print(a)
print(a.shape)
print(a.dtype)

[2.  4.  5.  4.5 7.6]
(5,)
float64


In [18]:
a=np.arange(10.8)
print(a)
print(a.shape)
print(a.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(11,)
float64


In [19]:
a=np.array([[2,4,5,8,7,5,],[4,6,5,3,7,8]])
print(a)
print(a.shape)
print(a.dtype)

[[2 4 5 8 7 5]
 [4 6 5 3 7 8]]
(2, 6)
int32


In [20]:
a=np.arange(20).reshape(4,5)
print(a)
print(a.shape)
print(a.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
int32


In [21]:
a=np.array([[2.3,4.4,6.5,8.9],[3.4,4.5,6.7,9.]])
print(a)
print(a.shape)
print(a.dtype)

[[2.3 4.4 6.5 8.9]
 [3.4 4.5 6.7 9. ]]
(2, 4)
float64


In [22]:
a=np.arange(18).reshape(6,3)
print(a)
print(a.shape)
print(a.dtype)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
(6, 3)
int32


In [23]:
a=np.array([[[2,4,5,6],[2,5,7,9]],[[3,5,7,5],[3,5,8,2]],[[2,4,5,6],[3,6,8,9]]])
print(a)
print(a.shape)
print(a.dtype)

[[[2 4 5 6]
  [2 5 7 9]]

 [[3 5 7 5]
  [3 5 8 2]]

 [[2 4 5 6]
  [3 6 8 9]]]
(3, 2, 4)
int32


In [24]:
a=np.arange(50).reshape(5,2,5)
print(a)
print(a.shape)
print(a.dtype)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]
(5, 2, 5)
int32


In [25]:
import numpy as np
a=np.array([[[2.4,3.4,5.5,6.1],[3.,5.1,7.2,9.5]],[[3.2,5.2,6.3,8.8],[3.,5.9,7.0,9.7]]])
print(a)
print(a.shape)
print(a.dtype)

[[[2.4 3.4 5.5 6.1]
  [3.  5.1 7.2 9.5]]

 [[3.2 5.2 6.3 8.8]
  [3.  5.9 7.  9.7]]]
(2, 2, 4)
float64


In [26]:
import numpy as np
a=np.arange(24).reshape(3,2,4)
print(a)
print(a.shape)
print(a.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
(3, 2, 4)
int32


In [27]:
import numpy as np

In [28]:

a=np.ones(9)
print(a)
print(a.shape)
print(a.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
(9,)
float64


In [29]:
a=np.ones((9,3),dtype=np.int32)
print(a)
print(a.shape)
print(a.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(9, 3)
int32


In [30]:
a=np.zeros(9)
print(a)
print(a.shape)
print(a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
(9,)
float64


In [31]:
a=np.zeros((9,4),dtype=np.int32)
print(a)
print(a.shape)
print(a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(9, 4)
int32


In [32]:
a=np.random.randint(6, size=88)
print(a)
print(a.shape)
print(a.dtype)

[0 0 2 5 2 2 3 4 5 2 3 1 2 3 3 3 5 3 4 4 1 2 0 4 3 1 1 5 0 0 0 1 4 0 4 0 0
 3 0 3 0 4 3 2 0 0 2 0 4 4 5 0 3 3 4 0 0 2 5 3 4 5 5 2 3 1 1 0 1 5 0 5 4 4
 3 1 2 3 3 2 0 3 1 0 0 0 4 2]
(88,)
int32


In [33]:
a=np.random.randint(6, size=(8,8))
print(a)
print(a.shape)
print(a.dtype)

[[1 3 2 4 2 5 0 4]
 [1 3 4 5 5 3 1 3]
 [3 4 0 0 0 5 2 4]
 [0 3 5 5 1 0 3 2]
 [5 5 5 2 5 3 3 2]
 [1 5 0 4 5 0 2 5]
 [1 4 2 1 1 5 0 0]
 [3 1 5 0 5 1 5 1]]
(8, 8)
int32


In [34]:
import numpy as np
a=np.random.randint(2.0,size=(2,3))
print(a)
print(a.shape)
print(a.dtype)


[[0 1 0]
 [0 0 1]]
(2, 3)
int32


In [35]:
a=np.random.randint(2,9,size=(5,7))
print(a)
print(a.shape)
print(a.dtype)

[[7 7 3 3 5 5 7]
 [8 7 8 3 5 7 6]
 [2 3 8 7 4 3 5]
 [8 3 7 7 8 8 5]
 [5 7 5 4 8 6 2]]
(5, 7)
int32


In [36]:
a=np.random.randint(1,[10,24,90])
print(a)
print(a.shape)
print(a.dtype)

[3 6 1]
(3,)
int32


In [37]:
a=np.random.randint([10,24,90],100)
print(a)
print(a.shape)
print(a.dtype)

[71 85 90]
(3,)
int32


In [38]:
a=np.random.randint([1,8,9],[10,24,90])
print(a)
print(a.shape)
print(a.dtype)

[ 3 12 71]
(3,)
int32


In [39]:
a=np.eye(3,3)
print(a)
print(a.shape)
print(a.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
float64


In [40]:
a=np.eye(3,3 ,dtype=np.int32)
print(a)
print(a.shape)
print(a.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)
int32


In [41]:
import numpy as np
a=np.random.randint(4,size=5)
print(a)

[0 0 1 1 2]


In [42]:
import numpy as np
b=np.random.randint(5,size=6)
b

array([2, 2, 2, 0, 4, 3])

In [43]:
b=np.random.randint(10)
print(b)

0


In [44]:
b=np.random.randint(10,size=6)
print(b)

[7 6 2 1 5 0]


In [45]:
b=np.random.randint(2,5, size=10)
print(b)

[3 2 4 3 4 3 3 3 4 3]


In [46]:
b=np.random.randint(2,7, size=(2,5))
print(b)

[[4 2 4 2 2]
 [5 2 3 4 5]]


In [47]:
b=np.random.randint(1,[2,4,5,6])
print(b)

[1 2 1 1]


In [48]:
b=np.random.randint([3,4,6],10)
print(b)

[5 7 8]


In [49]:
b=np.random.randint([1,5,7,8],[32,63,18,19])
print(b)

[ 8 56 14 11]


In [50]:
b=np.random.randint([[2,4,5,7],[3,15,16,17]],[[23,45,44,56],[66,49,56,74]])
print(b)

[[ 8  6 25 10]
 [10 30 26 24]]


In [51]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[1])

3


In [52]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[2])

5


In [53]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[2]+a[5])

10


In [54]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[1,5])

4


In [55]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[0,6])

9


In [56]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[0,1,2])

5


In [57]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[1,1,2])

4


In [58]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[0,1,2])

5


In [59]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-1])

9


In [60]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-4])

6


In [61]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-1]+a[-7])

11


In [62]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,6])

9


In [63]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-2,-4])

6


In [64]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[-1,-1,-2])

6


In [65]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[0,-1,2])

5


In [66]:
import numpy as np
a=np.array([[[2,3,5],[6,7,5]],[[1,2,4],[5,6,4]]])
print(a[-1,-2,2])

4


In [67]:
import numpy as np
a=np.array([[[2,3,5,5,7,5,4,6],[6,7,5,6,7,4,3,3]],[[1,2,4,8,5,4,2,4],[5,6,4,3,5,6,7,4]]])
print(a[0,1,-2])
print(a.shape)

3
(2, 2, 8)


In [68]:
import numpy as np
a=np.array([[[2,3,5,7,8],[6,7,5,4,7]],[[1,2,4,7,4],[5,6,4,6,3]]])
print(a[-1,-2,-5])

1


In [69]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[1:4])

[3 5 6]


In [70]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[1:])

[3 5 6 7 5 9]


In [71]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:1])

[2]


In [72]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[5:6])

[5]


In [73]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[::])

[2 3 5 6 7 5 9]


In [74]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[1:5:2])

[3 6]


In [75]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-1])

[2 3 5 6 7 5]


In [76]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-5:])

[5 6 7 5 9]


In [77]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-7 : -3])

[2 3 5 6]


In [78]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-4:-1])

[6 7 5]


In [79]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-1:-4])

[]


In [80]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-8:-1])

[2 3 5 6 7 5]


In [81]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[-6:])

[3 5 6 7 5 9]


In [82]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-5])

[2 3]


In [83]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-7])

[]


In [84]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-2])

[2 3 5 6 7]


In [85]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-5])

[2 3]


In [86]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-4])

[2 3 5]


In [87]:
import numpy as np
a=np.array([2,3,5,6,7,5,9])
print(a[:-3])

[2 3 5 6]


In [88]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,-4:-1])

[5 6 4]


In [89]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[1,1:5])

[2 4 5 6]


In [90]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[0,1:6])

[3 5 6 7 5]


In [91]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,6:])

[9]


In [92]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,2:])

[4 5 6 4 9]


In [93]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,5:])

[4 9]


In [94]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,-9:-6])

[1]


In [95]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[-1,-5:-2])

[4 5 6]


In [96]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[0:2,5])

[5 4]


In [97]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[0:2,-4])

[6 5]


In [98]:
import numpy as np
a=np.array([[2,3,5,6,7,5,9],[1,2,4,5,6,4,9]])
print(a[0:2,1:4])

[[3 5 6]
 [2 4 5]]


In [99]:
import numpy as np
a=np.array([2,4,4,5,6,7,8])
print(a)
b=a.copy()
print(b)
a[1]=44
print(a)
print(b)

[2 4 4 5 6 7 8]
[2 4 4 5 6 7 8]
[ 2 44  4  5  6  7  8]
[2 4 4 5 6 7 8]


In [100]:
import numpy as np
a=np.array([2,4,3,6,8,7])
print(a)
b=a.view()
print(b)
a[3]=44
print(a)
print(b)

[2 4 3 6 8 7]
[2 4 3 6 8 7]
[ 2  4  3 44  8  7]
[ 2  4  3 44  8  7]


In [101]:
a=np.array([2,4,7,8,9,8,99,19,10,3,1,12,14,13,18,6,44,55,10,35])
print("original array")
print(a)
print("make the reshape")
b=a.reshape(2,10)
print(b)
b2=a.reshape(4,5)
print(b2) 
b3=a.reshape(10,2)
print(b3)
b4=a.reshape(1,20)
print(b4)

original array
[ 2  4  7  8  9  8 99 19 10  3  1 12 14 13 18  6 44 55 10 35]
make the reshape
[[ 2  4  7  8  9  8 99 19 10  3]
 [ 1 12 14 13 18  6 44 55 10 35]]
[[ 2  4  7  8  9]
 [ 8 99 19 10  3]
 [ 1 12 14 13 18]
 [ 6 44 55 10 35]]
[[ 2  4]
 [ 7  8]
 [ 9  8]
 [99 19]
 [10  3]
 [ 1 12]
 [14 13]
 [18  6]
 [44 55]
 [10 35]]
[[ 2  4  7  8  9  8 99 19 10  3  1 12 14 13 18  6 44 55 10 35]]


In [102]:
a=np.array([2,4,7,8,9,8,99,19,10,3,1,12,14,13,18,6,44,55])
print("original array")
print(a)
b=a.reshape(3,2,3)
print("reshape 1D to 3D")
print(b)
b1=a.reshape(2,3,3)
print("reshape 1D to 3D")
print(b1)

original array
[ 2  4  7  8  9  8 99 19 10  3  1 12 14 13 18  6 44 55]
reshape 1D to 3D
[[[ 2  4  7]
  [ 8  9  8]]

 [[99 19 10]
  [ 3  1 12]]

 [[14 13 18]
  [ 6 44 55]]]
reshape 1D to 3D
[[[ 2  4  7]
  [ 8  9  8]
  [99 19 10]]

 [[ 3  1 12]
  [14 13 18]
  [ 6 44 55]]]


In [103]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
c=np.array([[[1,4,5],[4,6,7]],[[2,5,7],[2,5,6]],[[2,5,7],[2,7,9]]])
print(a)
print(np.sum(a))
print(np.sum(b))
print(np.sum(c))

[1 2 3 4 5]
15
54
86


In [104]:
import numpy as np
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
print(b)
print("add the element of all row")
print(np.sum(b, axis=0))
print("add the element of all colum")
print(np.sum(b, axis=1))


[[2 3 4 6 8]
 [2 6 8 9 6]]
add the element of all row
[ 4  9 12 15 14]
add the element of all colum
[23 31]


In [105]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
c=np.array([[[1,4,5],[4,6,7]],[[2,5,7],[2,5,6]],[[2,5,7],[2,7,9]]])
print(a)
print(np.mean(a))
print(b)
print(np.mean(b))
print(c)
print(np.mean(c))

[1 2 3 4 5]
3.0
[[2 3 4 6 8]
 [2 6 8 9 6]]
5.4
[[[1 4 5]
  [4 6 7]]

 [[2 5 7]
  [2 5 6]]

 [[2 5 7]
  [2 7 9]]]
4.777777777777778


In [106]:
a=np.array([[2,4,6,7,5,8],[4,5,6,7,3,1]])
print(a)
b=np.mean(a,axis=0)
print(b)
b=np.mean(a,axis=1)
print(b)


[[2 4 6 7 5 8]
 [4 5 6 7 3 1]]
[3.  4.5 6.  7.  4.  4.5]
[5.33333333 4.33333333]


In [107]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
c=np.array([[[1,4,5],[4,6,7]],[[2,5,7],[2,5,6]],[[2,5,7],[2,7,9]]])
print(a)
print(np.std(a))
print(b)
print(np.std(b))
print(c)
print(np.std(c))

[1 2 3 4 5]
1.4142135623730951
[[2 3 4 6 8]
 [2 6 8 9 6]]
2.416609194718914
[[[1 4 5]
  [4 6 7]]

 [[2 5 7]
  [2 5 6]]

 [[2 5 7]
  [2 7 9]]]
2.199887763691481


In [108]:
a=np.array([[2,4,6,7,5,8],[4,5,6,7,3,1]])
print(a)
b=np.std(a,axis=0)
print(b)
b=np.std(a,axis=1)
print(b)


[[2 4 6 7 5 8]
 [4 5 6 7 3 1]]
[1.  0.5 0.  0.  1.  3.5]
[1.97202659 1.97202659]


In [109]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
c=np.array([[[1,4,5],[4,6,7]],[[2,5,7],[2,5,6]],[[2,5,7],[2,7,9]]])
print(a)
print(np.var(a))
print(b)
print(np.var(b))
print(c)
print(np.var(c))

[1 2 3 4 5]
2.0
[[2 3 4 6 8]
 [2 6 8 9 6]]
5.839999999999999
[[[1 4 5]
  [4 6 7]]

 [[2 5 7]
  [2 5 6]]

 [[2 5 7]
  [2 7 9]]]
4.839506172839506


In [110]:
a=np.array([[2,4,6,7,5,8],[4,5,6,7,3,1]])
print(a)
b=np.var(a,axis=0)
print(b)
b=np.var(a,axis=1)
print(b)


[[2 4 6 7 5 8]
 [4 5 6 7 3 1]]
[ 1.    0.25  0.    0.    1.   12.25]
[3.88888889 3.88888889]


In [111]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3,4,6,8],[2,6,8,9,6]])
c=np.array([[[1,4,5],[4,6,7]],[[2,5,7],[2,5,6]],[[2,5,7],[2,7,9]]])
print(a)
print(np.min(a))
print(b)
print(np.min(b))
print(c)
print(np.min(c))

[1 2 3 4 5]
1
[[2 3 4 6 8]
 [2 6 8 9 6]]
2
[[[1 4 5]
  [4 6 7]]

 [[2 5 7]
  [2 5 6]]

 [[2 5 7]
  [2 7 9]]]
1


In [112]:
a=np.array([[2,4,6,7,5,8],[4,5,6,7,3,1]])
print(a)
b=np.min(a,axis=0)
print(b)
b=np. min(a,axis=1)
print(b)


[[2 4 6 7 5 8]
 [4 5 6 7 3 1]]
[2 4 6 7 3 1]
[2 1]


In [113]:
m=np.array([2,5,6,8,9,48])
print(m)
a=np.max(m)
print(a)
n=np.array([[1,4,6,8,4,6],[3,6,5,7,8,9]])
print(n)
b=np.max(n)
print(b)
o=np.array([[[2,3],[7,3]],[[3,4],[4,6]],[[2,7],[5,6]]])
print(o)
c=np.max(o)
print(c)

[ 2  5  6  8  9 48]
48
[[1 4 6 8 4 6]
 [3 6 5 7 8 9]]
9
[[[2 3]
  [7 3]]

 [[3 4]
  [4 6]]

 [[2 7]
  [5 6]]]
7


In [114]:
a=np.array=([[5,6,8,3,5],[2,4,6,8,9]])
print(a)
b=np.max(a,axis=1)#one for colum
print(b)
c=np.max(a,axis=0)# zero for row
print(c)

[[5, 6, 8, 3, 5], [2, 4, 6, 8, 9]]
[8 9]
[5 6 8 8 9]


In [116]:
import mysql.connector as con

In [117]:
import mysql.connector as con 
new_db=con.connect(
    host="localhost",
    user="root",
    password="tiger"
)
print(new_db)

In [119]:
import mysql.connector as con
new_db=con.connect(
    host="localhost",
    user="root",
    password="tiger",
    database="college"
)
new_cursor=new_db.cursor()
new_cursor.execute("create table student (sanme VARCHAR(200),rollno VARCHAR(10),SEM INT)")

ProgrammingError: 1050 (42S01): Table 'student' already exists

In [ ]:
import mysql.connector as con
new_db=con.connect(
    host="localhost",
    user="root",
    password="tiger",
    database="college"
)
new_cursor=new_db.cursor()
new_cursor.execute("SHOW TABLES")
for i in new_cursor:
    print(i)

In [120]:
import numpy as np
a=np.array([4,7,8,9,5,8,4])
print(a)
print(a.shape)
print(a.dtype)


TypeError: 'list' object is not callable

In [121]:
import numpy as np
a=np.arange(10)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


In [122]:
import numpy as np
a=np.array([2.4,5.6,7.8,5.5])
print(a)
print(a.shape)
print(a.dtype)

TypeError: 'list' object is not callable

In [123]:
import numpy as np
a=np.arange(10000)
a=a*a
print(a)

[       0        1        4 ... 99940009 99960004 99980001]


In [124]:
import numpy as np
a=np.array(['dog','cat','cow','pig','donkey',23,4,5])
print(a)

TypeError: 'list' object is not callable

In [125]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [126]:
a=np.zeros((2,3),dtype="int32" )
print(a)

[[0 0 0]
 [0 0 0]]


In [127]:
import numpy as np
a=np.random.randint(20)
print(a)

TypeError: 'list' object is not callable

In [128]:
import numpy as np
a=np.random.randn(20)
print(a)

[ 1.23059681  0.03334702 -2.04256816 -0.13843691  0.7920107   0.38098161
 -1.05432292  1.65079011 -1.32717417 -0.22841254  0.24654893 -0.40691999
  0.35585894  0.39667071  0.79923823 -0.9137844  -2.20289565  0.53491752
  0.5406753   0.7668966 ]


In [129]:
import numpy as np
a=np.random.rand(20)
print(a)

[0.59972594 0.18092676 0.92213895 0.78448243 0.00919961 0.25028502
 0.85739929 0.94038919 0.92482226 0.1265567  0.67392579 0.37287168
 0.1994359  0.14260086 0.65716464 0.38017329 0.77240939 0.82623427
 0.00677    0.8964096 ]


In [130]:
a=np.array([[2,3,5,6,8,3],[2,4,6,7,8,5]])
print(a)
b=a.reshape(2,3,2)
print(b)

TypeError: 'list' object is not callable

In [131]:
print("original array")
a=np.array([3,5,6,4,5,6])
print(a)
print("using arg short")
print(a.argsort())
print("print the value in assending order")
print(a[a.argsort()])
print("original array")
print(a)

original array


TypeError: 'list' object is not callable

In [132]:
import numpy as np
a=np.array([1,5,4,6,7,8])
b=np.array([9,8,6,7,4,7,4])
print(a[short_index])

TypeError: 'list' object is not callable

In [133]:
import numpy as np
a=np.array([2,8,7,5,9,3,4])
print(a)
print(a.argsort())
b=a[a.argsort()]
print(b)
c=list(a[a.argsort()])
print(c)
d=(list(a[np.argsort(a)])[::-1])
print(d)

TypeError: 'list' object is not callable

In [134]:
a=np.array([2,9,8,17,65,44,6,7,4,2,3])
print("original data is:",a)
c=(np.argsort(a))
print(c)
d=a[np.argsort(a)]
print(d)
e=list(a[np.argsort(a)])
print(e)
d=(list(a[np.argsort(a)])[::-1])
print(d)

TypeError: 'list' object is not callable

In [135]:
import numpy.random as npr
a=npr.random(10)
print(a)

[0.97555694 0.33068408 0.37494495 0.00278946 0.50355507 0.24581405
 0.73984001 0.76508343 0.55290003 0.07456055]


In [136]:
import numpy.random as npr
a=npr.randint(10)
print(a)

TypeError: 'list' object is not callable

In [137]:
import numpy.random as npr
a=npr.randint(-3,7,size=(100))
print(a)

TypeError: 'list' object is not callable

In [138]:
import numpy.random as npr
a=np.clip(a,-4,0)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [139]:
import numpy.random as npr
a.clip(0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
a=npr.randint(-2,5,200)
print(a)

In [ ]:
import numpy as np
import numpy.random as npr
b=np.clip(a,-4,2)
print(b)

In [ ]:
a.clip(0)

In [ ]:
import numpy as np

In [ ]:
import numpy as np
import numpy.random as npr
a=npr.randint(-4,9 ,size=100)
print(a)

In [ ]:
b=np.clip(a,-4,3)
print(b)

In [ ]:
import numpy as np
import numpy.random as npr
c=a.clip(0)
print(c)
d=b.clip(0)
print(d)

In [ ]:
npr.choice(a,20)

In [ ]:
np.unique(a)

In [ ]:
len(np.unique(a))

In [ ]:
import numpy as np
a=np.random.randn(7,6)
a

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.head()

In [ ]:
df.head(3)

In [ ]:
df.tail()

In [ ]:
df.tail(3)

In [ ]:
pd.options.display.max_rows=6 
df

In [ ]:
df.columns=["a","b","c","d","e","f"]
df

In [ ]:
index=pd.date_range('1/1/2022',periods=7)

In [ ]:
df.set_index(index,inplace=True)
df

In [ ]:
df['a']

In [ ]:
df[['a']]

In [ ]:
df.a

In [ ]:
df[['a','c']]

In [ ]:
df[['a','c','f','e']]

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[[0,3,4]]

In [ ]:
df.iloc[0,:3]

In [ ]:
df.iloc[5, :]

In [ ]:
df.iloc[0,:]

In [ ]:
df.iloc[:,4]

In [ ]:
df.loc['2022-01-01']

In [ ]:
df.loc['2022-01-05','e':]

In [ ]:
df.loc[:,'e':]

In [ ]:
df.loc['2022-01-03':,:]

In [ ]:
df <0

In [ ]:
mask=df<0
df[mask]=0
df

In [ ]:
df.describe()

In [ ]:
import pandas as pd
p=pd.Series([2,4,5,6,8,4])
print(p)
d=pd.Series(['A','S','C','E','Y','O'])
print(d)

In [ ]:
import pandas as pd

In [ ]:
a=pd.Series([3,5,6,7,8,9,0],index=['A','B','C','D','E','F','G'])
print(a)

In [ ]:
i=pd.Index(['Pooja','Laxmi','varsha','prachi','nandini','Sneha','manju','Varshag','Neha'])
a=pd.Series([98,99,98,97,96,97,96,95,94],index=i)
a

In [ ]:
a=pd.Series({'pooja':98,'Laxmi':99,'Varsha':98,'Prachi':97,'Neha':94})
print(a)

In [ ]:
import numpy as np
a=np.arange(30).reshape(6,5)
b=pd.DataFrame(a,index=['Aman','Amit','Ajay','Avinash','Amar','Anita'],columns=['Kannada','English','Hindi','Science','Maths'])
b

In [ ]:
a=np.array([[2,5,4,6,7,8],[2,4,5,6,7,5],[4,5,6,7,8,6]])
df=pd.DataFrame(a,index=['maths','Kannada','English'],columns=['a','b','c','d','e','f'])
df

In [ ]:
a=pd.DataFrame([
    [2,5,6,8,5,6],
    [2,3,4,5,6,8],
    [2,4,6,7,8,4],
    [3,6,5,7,8,5],
    [3,6,8,4,9,1]
],columns=['Rahul','Ramesh','Rani','Rakesh','Roshani','Rekha'],index=['Kannada','English','Hindi','Science','Maths'])
a

In [ ]:
a=pd.DataFrame({'Rahul':[99,55,63,44,],'Rmesha':[97,44,34,55],'Rani':[98,44,34,23],'Rakesh':[96,45,67,89],'Roshani':[97,43,54,65],'Rekha':[94,54,65,76]},index=['Kannada','English','Maths','Science'])
a

In [ ]:
srs1=pd.Series([2,4,6,8,5])
srs2=pd.Series([3,5,7,9,4])
ans=pd.DataFrame({'osa':srs1,'Java':srs2})
ans

In [ ]:
import pandas as pd
import numpy as np
a=pd.Series([2,4,5],index=['Karnataka','Gujarat','Goa'],name='poputation')
b=pd.Series(['Bengaloru','Gandinagar','Panji'],index=['Karnataka','Gujarat','Goa'],name='capital')
df=pd.DataFrame({'poputation':a,'capital':b})
df.to_csv('df1.csv')

In [ ]:
df1

In [ ]:
df1=pd.DataFrame([
    ['32.4','bengaloru'],
    ['34.6','Gandinagar'],
    ['45.9','Panji']
],index=['Karnataka','Gujarat','Goa'],columns=['population','capital'])
print(df1.append(pd.DataFrame([['78.9','patna'],['32.5','silang']],index=['bihar','meghalay'],columns=['population','capital'])))

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame([
    [23,45,66,78],
    [34,56,78,45],
    [34,56,75,89],
    [34,65,76,87]
],columns=['OSA','JAVA','DSP','SE'])
df

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.sum()

In [ ]:
df.max()

In [ ]:
df.min()

In [ ]:
df.mean()

In [ ]:
df.median()

In [ ]:
df.std()

In [ ]:
df.var()

In [ ]:
df.count()

In [ ]:
df.cumsum()

In [ ]:
a.agg(['sum','min','max','median'])

In [ ]:
import pandas as pd
import numpy as np
a=pd.read_csv("titanic.csv")
a

In [ ]:
a.describe()

In [ ]:
a.info()

In [ ]:
a.columns

In [ ]:
a.index

In [ ]:
a.head()

In [ ]:
a.head(9)

In [ ]:
a.tail()

In [ ]:
a.tail(4)

In [ ]:
a.isnull()

In [ ]:
a.isnull().sum()

In [ ]:
a[["Age"]].isnull()

In [ ]:
a[["Age"]].isnull().sum()

In [ ]:
a[["Age"]].isnull().mean()

In [ ]:
a[["Age","Survived"]].isnull()

In [ ]:
a[["Age","Survived"]].isnull().mean()

In [ ]:
df3=a.drop(["SibSp","PassengerId","Fare",'Name'],axis=1)
df3

In [ ]:
d=a.groupby('Survived')['Survived'].count()
print(d)

In [ ]:
d=a.groupby('Pclass')['Pclass'].count()
d

In [ ]:
c=a.groupby('Sex')['Sex'].count()
c

In [ ]:
d=a.groupby('Embarked')['Embarked'].count()
d

In [ ]:
d=a.groupby('Sex')['Survived'].sum()
d

In [ ]:
d=a.groupby(['Pclass','Sex','Survived'])['Survived'].count()
d

In [ ]:
e=a.groupby('Pclass')['Survived'].sum()
e

In [ ]:
e=a.groupby('Pclass')['Survived'].count()
e

In [ ]:
f=a.groupby('Pclass')['Survived'].sum()/a.groupby('Pclass')['Survived'].count()*100
f

# PIVOT TABLE

In [ ]:
ab=a.pivot_table(values="Survived",index=['Pclass'],aggfunc='sum')
ab

In [ ]:
ab=a.pivot_table(values='Survived',index='Sex',columns='Pclass',aggfunc='sum')
ab

In [ ]:
ab=a.pivot_table(values="Survived",index='Sex',columns="Pclass",aggfunc='count')
ab

In [ ]:
ad=a.pivot_table(values='Survived',index='Sex',columns='Pclass')
ab

In [ ]:
ad=a.pivot_table(values="Survived",index='Sex')
ab

In [ ]:
ab=a.pivot_table(values='Survived',index=['Sex','Age'],columns='Pclass',aggfunc='sum')
ab

In [ ]:
ab=a.pivot_table(values='Survived',index=['Sex','Age'],columns='Pclass',aggfunc='count')
ab

In [ ]:
import numpy as np
import pandas as pd
a=pd.DataFrame([
    ['Aryan','singh','Fulltime','Administration',2,20000],
    ['Rohan','Agrawal','Intern','Technical',3,3500],
    ['Rijya','Shah','Fulltime','Adminisration',5,10000],
    ['Yash','Bhatia','Part_time','Technical',7,10000],
    ['Sidhant','Khana','Fulltime','Manager',6,20000]
],columns=['First_Name','Last_name','type','Department','Yoe','Salary'])
a

In [ ]:
ab=a.pivot_table(index="type")
ab

In [ ]:
ab=a.pivot_table(values='Salary',index='type',aggfunc='sum')
ab

In [ ]:
ab=a.pivot_table(values='Salary',index='type',columns='Department',aggfunc='sum')
ab

In [ ]:
ab=a.pivot_table(values='Salary',index='type',columns='Department',aggfunc='count')
ab

In [ ]:
ab=a.pivot(values='Salary',index='type',columns='Department')
ab

In [ ]:
ab=a.pivot_table(values='Salary',index='type',aggfunc=(['sum','count','mean']))
ab

In [ ]:
ab=a.pivot_table(values='Cabin',index='Sex',columns='Pclass',aggfunc='count')
ab

In [ ]:
import pandas as pd
import numpy as np
df1=pd.read_excel("SaleData.xlsx")
df1

In [ ]:
#1
a=df1.pivot_table(index=["Region","Manager","Units"])
a

In [ ]:
#2
a=df1.pivot_table(values='Sale_amt',index=["Region","Manager"],aggfunc='sum')
a

In [ ]:
#3
a=df1.pivot_table(values="Sale_amt",index=["Region","Manager","SalesMan"],aggfunc='sum')
a

In [ ]:
#3
a=df1.groupby(['Manager','SalesMan','Region'])['Sale_amt'].agg(['sum','count'])
a

In [ ]:
#4
a=df1.pivot_table(values='Units',index='Item',aggfunc='sum')
a

In [ ]:
#5
a=df1.pivot_table(values="Sale_amt",index='Region',aggfunc='sum')
a

In [ ]:
#6
a=df1.pivot_table(values='Units',index=['Region','Item'],aggfunc='sum')
a

In [ ]:
#7
a=df1.pivot_table(values="Sale_amt",index='Manager',aggfunc=(['count','mean']))
a

In [ ]:
#8
a=df1.pivot_table(values='Sale_amt',index='SalesMan',aggfunc='sum',margins='True', margins_name='Total')
a

In [ ]:
#9
a=df1.pivot_table(values='Sale_amt',index=['Region','Manager','SalesMan'],aggfunc='sum')
a.query ('Manager == ["Douglas"]')


In [ ]:
#10
a=df1.pivot_table(values='Sale_amt',index='Item',aggfunc='max')
a

In [ ]:
#12
a=df1.pivot_table(values='Sale_amt',index='Item',aggfunc='min')
a

In [ ]:
#13
a=df1.pivot_table(values='Sale_amt',index='Item',aggfunc=(['max','min']))
a

In [ ]:
a.pivot_table(index='name',columns='osa',aggfunc='sum',fill_value='Not need', margins = True)

In [ ]:
import pandas as pd
a=pd.DataFrame([
    ['Arun',23,45,45,34],
    ['Aman',23,56,78,67],
    ['Ajay',34,56,78,66],
    ['Aksah',23,67,89,56]
],columns=['name','osa','java','Se','Dsa'])
print(a)
a.melt(id_vars=['name'])

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
a=Series([2,4,5,7,3])
b=Series([1,2,3,4,5],index=[0,1,2,3,4])


In [ ]:
print(a)

In [ ]:
print(b)

In [ ]:
a+b

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
a-b

In [ ]:
a**b

In [ ]:
a>b

In [ ]:
a<b

In [ ]:
a==b

In [ ]:
a>=b

In [ ]:
a<=b

In [ ]:
a!=b

In [ ]:
np.sqrt(a)

In [ ]:
np.abs(a)

In [ ]:
type(np.abs(a))

In [ ]:
@np.vectorize
def trunc(x):
    return x if x>0 else 0
trunc(x=np.array([2,5,-6,3,4,1]))

In [ ]:
trunc(b)

In [ ]:
type(trunc(b))

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
a=pd.Series([2,4,6,4,5])
b=pd.Series([3,2,5,8,9])
plt.plot(a,b)
plt.show()

In [ ]:
import matplotlib.pyplot as plt
a=[2,4,6,7,8,9]
b=[2,5,7,4,3,2]
plt.plot(a,b)
plt.title("First chart",color='m',fontsize=45)
plt.show()

In [ ]:
a=[2,5,4,3,4]
b=[3,5,7,6,5]
plt.plot(a,b)
plt.title("Second chart",color='g',fontsize=45)
plt.xlabel('Roll number')
plt.ylabel('Reg number')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
a=[2,5,4,6,7,8]
b=[3,6,8,7,9,4]
plt.plot(a,b)
plt.title("Third chart",color='m',fontsize=45)
plt.xlabel("Rolenumber")
plt.ylabel("Reg number")
plt.xlim(0,10)
plt.ylim(0,20)
plt.show()

In [ ]:
a=[2,4,5,6,7,3]
b=[2,4,5,6,7,8]
plt.plot(a,b)
plt.title("forth",color='r',fontsize=29)
plt.xlabel("rollnumber",color='k',fontsize=15)
plt.ylabel("reg number",color='k',fontsize=15)
plt.xlim(1,10)
plt.ylim(1,10)
plt.xticks(np.arange(1,11,1))
plt.yticks(np.arange(1,11,1))
plt.show()

In [ ]:
a=[2,4,5,6,7,3]
b=[2,4,5,6,7,8]
plt.plot(a,b)
plt.title("forth",color='r',fontsize=29)
plt.xlabel("rollnumber",color='k',fontsize=15)
plt.ylabel("reg number",color='k',fontsize=15)
plt.xlim(1,10)
plt.ylim(1,10)
plt.xticks(np.arange(1,11,1))
plt.yticks(np.arange(1,11,1))
plt.legend(['Java'])
plt.show()

In [ ]:
a=[1,5,6,7,3,5,6]
b=[10,40,64,40,71,81,93]
i= plt.figure(figsize =(8, 7), facecolor='r', edgecolor='g', linewidth=20)  
plt.plot(a,b)
plt.title("hello hi",color='b',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,30)
plt.xlabel("Hello")
plt.ylabel("hi")
plt.xticks(np.arange(1,11,1))
plt.yticks(np.arange(1,100,5))
plt.legend(['Java'])
plt.show()

In [ ]:
a=[2,4,5,7,8,5]
b=[3,5,6,4,7,8]
fig=plt.figure(figsize=(6,5),facecolor='g',edgecolor='r',linewidth=20)
ax=fig.add_axes([1,1,1,1])
plt.plot(a,b)
plt.xlabel("Rollnumber")
plt.ylabel("marks")
plt.xlim(1,10)
plt.ylim(1,10)
plt.xticks(np.arange(1,9,1))
plt.yticks(np.arange(1,9,1))
plt.legend(['java'])
plt.show()

# creating line bar graph

In [ ]:
a=[2,5,7,8,9]
b=[3,5,6,7,8]
plt.plot(a,b)
plt.title("BarGraph",color='r',fontsize=35)
plt.xlabel("Rollnumber")
plt.xlabel("MArks")
plt.show()

In [ ]:
a=[2,4,6,7,8,9]
b=[3,4,2,6,5,7]
plt.plot(a, b, color='k', linewidth=4, marker='4', markersize=35,  linestyle='dotted')
plt.title("other type of line bar",color='r',fontsize=30)
plt.xlabel("ROll number")
plt.ylabel("Marks")
plt.show()

In [ ]:
a=[2,4,6,7,8,9]
b=[3,4,2,6,5,7]
plt.plot(a, b, color='g', linewidth=3, marker='o', markersize=13, markerfacecolor='r',  linestyle='dashed')
plt.title("other type of line bar",color='r',fontsize=30)
plt.xlabel("ROll number")
plt.ylabel("Marks")
plt.show()

In [ ]:
a=[1,2,3,4,5,6,7]
b=[3,5,6,8,3,5,6]
plt.bar(a,b)
plt.title("marks of java",color='r',fontsize=23)
plt.xlabel("rollnumber")
plt.ylabel("marks")
plt.legend("java")
plt.show()

In [ ]:
a=[1,2,3,4,5,6,7]
b=[3,5,6,8,3,5,6]
tick_label=['one','two','three','four','five','six','seven']
plt.bar(a , b , tick_label=tick_label, color=['r','c'],width=0.5, edgecolor='k',linewidth=5)
plt.title("marks of java",color='c',fontsize=23)
plt.xlabel("rollnumber")
plt.ylabel("marks")
plt.legend("java")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
a=[1,12,35,4,55,6,70,81,90,10]
DSP=[32,23,45,67,12,45,78,90,67,89]
OSA=[23,54,67,89,23,45,34,21,34,21]
JAVA=[12,34,56,34,23,12,34,23,67,89]
SE=[21,54,67,89,56,78,34,23,21,44]
fig=plt.figure(figsize=(15,5),facecolor='red',edgecolor='g',linewidth=24)
plt.subplot(1,4,1)
plt.title("Width")
plt.plot(a,DSP)

plt.subplot(1,4,2)
plt.title("scond")
plt.plot(a,OSA)

plt.subplot(1,4,3)
plt.title("third")
plt.plot(a,JAVA)

plt.subplot(1,4,4)
plt.title("fourth")
plt.plot(a,SE)

plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,6,7,2,3]
fig=plt.figure(figsize=(5,4))

ax1=fig.add_axes([1, 2, 1, 1])
plt.plot(a,b)

ax2=fig.add_axes([2.1,2,1.1,1])
plt.plot(a,b)

ax3=fig.add_axes([1, 0.9, 1, 1])
plt.plot(a,b)


ax4=fig.add_axes([2.1,0.9,1,1])
plt.plot(a,b)
plt.show()

In [ ]:
a=[2,3,5,7,8,9,5]
da=[4,5,7,8,9,4,5]
osa=[2,3,4,7,6,8,9]
java=[3,5,7,9,8,7,5]
se=[3,6,7,9,6,5,3]
fig=plt.figure(figsize=(15,5),facecolor='r',edgecolor='g',linewidth=24)
plt.subplot(1,4,1)
plt.title("first")
plt.plot(a,da)

plt.subplot(1,4,2)
plt.title("second")
plt.plot(a,osa)

plt.subplot(1,4,3)
plt.title("third")
plt.plot(a,java)

plt.subplot(1,4,4)
plt.title("fourth")
plt.plot(a,se)

In [ ]:
a=[2,4,6,7,8,9]
b=[2,5,4,6,7,9]
plt.plot(a,b)
plt.title("first")
plt.xlabel("first x axis")
plt.ylabel("second y axis")
plt.show(a,b)

In [ ]:
a=[2,5,6,8,4,5,9]
b=[2,5,6,9,8,2,3]
plt.plot(a,b, color='green',marker='o',markersize=15,markerfacecolor='red',linestyle='dashed',linewidth=3)
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("BAR CHART", color='r', fontsize=23)
plt.show(a,b)

In [ ]:
a=[3,5,6,8,9,2]
b=[3,5,8,9,4,3]
plt.bar(a,b,color='r',edgecolor='green',width=0.9,linewidth=2.3)

In [ ]:
a=np.random.randint(1,50,100)
plt.hist(a)

In [ ]:
a=[2,3,0,4,5,6]
b=[2,4,6,7,8,3]
plt.scatter(a,b)
plt.show()

In [ ]:
a=[2,4,5,7,9,4]
b=[3,6,8,2,3,9]
plt.scatter(a,b,marker='o',edgecolor='g',s=200,alpha=0.9,color='r')

In [ ]:
a=[20,10,20,30,20]
b=['osa','java','se','DSA','PP']
plt.pie(a,labels=b)
plt.show()

# Visualizing amount

# 1.using matplotlib bar chart display Total amout of sales region wise. 

In [ ]:
a=df.groupby('Region')['Units'].sum()
plt.bar(a.index,a)

# 1.using matplotlib bar chart display the item wise unit sold.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_excel('SaleData.xlsx')
print(df)
a=df.groupby('Item')['Units'].sum()
plt.bar(a.index,a)
plt.show()

# 2.using matplotlib bar chart display the total sales by managers.

In [ ]:
a=df.groupby('Manager')['Sale_amt'].sum()
plt.bar(a.index,a)
plt.show()

# 3.using matplotlib bar chart display the total sales by salesman.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

a=df.groupby('SalesMan')['Sale_amt'].sum()
plt.bar(a.index,a)

# 4.using matplotlib bar chart display Total male & female in titanic ship. 


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('titanic.csv')
a=df.groupby('Sex')['Sex'].count()
plt.bar(a.index,a)
plt.show()
df

# 5.using matplotlib bar chart display Total male & female survived in titanic ship.

In [ ]:
a=df.groupby('Sex')['Survived'].sum()
plt.bar(a.index,a)
plt.show()


# 6.using matplotlib bar chart display class wise pasergers titanic ship.

In [ ]:
a=df.groupby('Pclass')['PassengerId'].count()
plt.bar(a.index,a)
plt.show()

# create histogram of the age in taitanic sheep 

In [ ]:
plt.hist(df['Age'])
plt.show()

In [ ]:
a=[2,6,7,8,9,4]
b=[3,6,8,7,9,3]
plt.plot(a,b)
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
plt.plot(a,b)
plt.title("First chart",color='r',fontsize=23)

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.xlabel("X axis")
plt.ylabel("y axis")
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.xlabel("x")
plt.ylabel("Y")
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.xlabel("x")
plt.ylabel("Y")
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.legend('osa')
plt.show()

# creaing window

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
fig=plt.figure(figsize=(15,7),facecolor='red',edgecolor='g',linewidth=32)
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.xlabel("x")
plt.ylabel("Y")
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.show()

# plot creation

In [ ]:
a=[1,2,3,4,5,6]
b=[3,5,7,8,5,6]
fig=plt.figure(figsize=(10,5),facecolor='red',edgecolor='g',linewidth=32)
ax3=fig.add_axes([1,1,1,1])
plt.plot(a,b)
plt.title("Second chart",color='r',fontsize=34)
plt.xlim(0,10)
plt.ylim(0,10)
plt.xlabel("x")
plt.ylabel("Y")
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.show()

# plot creation

# sub plot

In [ ]:
a=[1,3,5,7,5,4,6,4]
osa=[2,4,5,6,7,8,9,5]
java=[2,4,5,7,8,5,4,3]
se=[3,6,7,8,9,3,4,5]
fig=plt.figure(figsize=(15,4), facecolor='red',edgecolor='g',linewidth=20)
plt.subplot(1,4,1)
plt.title("first")
plt.plot(a,osa)

plt.subplot(1,4,2)
plt.title("second")
plt.plot(a,java)

plt.subplot(1,4,3)
plt.title("se")
plt.plot(a,se)

In [ ]:
a=[1,2,3,4,5]
b=[4,5,6,7,8]
fig=plt.figure(figsize=(5,3),facecolor='r',edgecolor='g',linewidth=32)
ax1=fig.add_axes([1,1,1,1])
plt.plot(a,b
        )
fig=plt.figure(figsize=(5,3),facecolor='r',edgecolor='g',linewidth=32)
ax2=fig.add_axes([1,1,1,1])
plt.plot(a,b)

fig=plt.figure(figsize=(5,3),facecolor='r',edgecolor='g',linewidth=32)
ax1=fig.add_axes([1,1,1,1])
plt.plot(a,b)

fig=plt.figure(figsize=(5,3),facecolor='r',edgecolor='g',linewidth=32)
ax1=fig.add_axes([1,1,1,1])
plt.plot(a,b)

# line chart

In [ ]:
a=[1,2,3,4,5,6]
b=[4,7,4,8,3,9]
plt.bar(a,b)
plt.title("line bar")
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[5,6,3,7,8,9]
plt.bar(a,b,color='r',edgecolor='g',width=0.5,linewidth=4)

In [ ]:
a=[1,2,3,4,5,6]
b=[2,5,7,8,5,9]
plt.plot(a,b)
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[2,5,7,8,5,9]
plt.plot(a,b, marker='o', markersize=13, markerfacecolor='r',linestyle='dashed',linewidth=2,color='g')
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.show()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a=[1,2,3,4,5]
b=[2,3,4,7,5]
plt.plot(a,b)
plt.show()

In [ ]:
a=[1,2,3,4,5]
b=[2,3,4,7,5]
plt.plot(a,b)
plt.title("first chart",color='g',size=34)

In [ ]:
a=[1,2,3,4,5]
b=[2,3,4,7,5]
plt.plot(a,b)
plt.title("first chart",color='g',size=34)
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.show()

In [ ]:
a=[1,2,3,4,5]
b=[2,3,4,7,5]
plt.plot(a,b)
plt.title("first chart",color='g',size=34)
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.xlim(1,10)
plt.ylim(1,10)
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.legend(['OSA'])
plt.show()

In [ ]:
a=[1,2,3,4,5,6]
b=[2,3,4,7,5,9]
fig=plt.figure(figsize=(10,5),facecolor='r',edgecolor='g',linewidth=45)
plt.plot(a,b)
plt.title("first chart",color='c',size=34)
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.xlim(1,10)
plt.ylim(1,10)
plt.xticks(np.arange(1,10,1))
plt.yticks(np.arange(1,10,1))
plt.legend(['OSA'])
plt.show()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
a=[1,2,3,4,5,6,7,8,9,0]
osa=[34,56,45,56,23,45,78,89,67,56]
java=[12,34,54,56,45,65,76,89,87,65]
se=[12,34,32,34,13,56,76,85,95,64]
dsp=[23,43,54,12,32,41,23,23,12,34]

plt.subplot(2,1,1)
plt.plot(a,osa)
plt.show()

plt.subplot(2,2,1)
plt.plot(a,java)
plt.show()

In [ ]:
import numpy as np
import pandas as ps
from datetime import datetime
df=pd.date_range(start="10/1/2011",end="11/1/2011",freq="min")
df1=pd.DataFrame(df,columns=["Data_time"])
df1

In [ ]:
import numpy as np
import pandas as ps
from datetime import datetime
df=pd.date_range(start="10/1/2011",end="11/1/2011",freq="min")
df1=pd.DataFrame(df,columns=["Data_time"])
df1["data"]=np.random.randint(1,100,size=(len(df)))
df1

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime
time = pd.date_range(start ='10/1/2022', end ='11/1/2022',freq ='Min')
df = pd.DataFrame(time, columns=['DateTime'])
df['DATA'] = np.random.randint(0,100,size=(len(time)))
print(df)
df.head()
#df.head(20)

In [ ]:
import numpy as np
a=pd.Series(["cat","Dog",np.nan,"lion"])
a

In [ ]:
a.map({"cat":"citten","Dog":"puppy"})

In [ ]:
a=pd.Series(["cat","Dog",np.nan,"cow"])
a

In [ ]:
a.map({"cat":"kitten","Dog":"Puppy"})

In [ ]:
a.map({"cat":"kitten","Dog":"Puppy","cow":"cub"})

In [ ]:
a.map("I Am A {}".format)

In [ ]:
a.map("I Am A {}".format ,na_action="ignore")

In [ ]:
def addition(a):
    return a+4
num=(2,5,48,3)
res=map(addition,num)
print(list(res))

In [ ]:
def addition(a):
    return a+4
num=(2,5,48,3)
res=map(addition,num)
for i in res:
    print(i)
print(type(res))

In [ ]:
def squ(n):
    return n*n
num=(2,5,7)
res=map(squ,num)
print(list(res))
for i in res:
    print(i)

In [ ]:
a=[1,4,6,5,7,8,9,5,7]
result=filter(lambda a1: if a1%2 != 0,a)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
a = sns.load_dataset('tips')
a

In [ ]:
sns.scatterplot(x='total_bill',y='tip',data=a)

In [ ]:
sns.scatterplot(x="total_bill",y="tip",data=a,hue="sex")

In [ ]:
sns.scatterplot(x="total_bill",y="tip",data=a,hue="sex",size="size")

In [ ]:
sns.scatterplot(x="total_bill",y="tip",data=a,hue="sex",style="smoker",size="size")

In [ ]:
import matplotlib.pyplot as plt
ab=pd.read_csv("titanic.csv")
s=ab.groupby("Pclass").mean()["Survived"]*100
a.plot(kind='bar')