In [577]:
import numpy as np
import pandas as pd

In [578]:
a=pd.read_csv("dataset/titanic.csv")

In [579]:
a

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [580]:
a.drop(['PassengerId','Name','Ticket','Fare','Cabin'],inplace=True,axis=1)

In [581]:
a

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0           0       3    male  22.0      1      0        S
1           1       1  female  38.0      1      0        C
2           1       3  female  26.0      0      0        S
3           1       1  female  35.0      1      0        S
4           0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0        S
887         1       1  female  19.0      0      0        S
888         0       3  female   NaN      1      2        S
889         1       1    male  26.0      0      0        C
890         0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [582]:
a=a.dropna(subset=['Embarked'])

In [583]:
a.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      0
dtype: int64

In [584]:
a

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0           0       3    male  22.0      1      0        S
1           1       1  female  38.0      1      0        C
2           1       3  female  26.0      0      0        S
3           1       1  female  35.0      1      0        S
4           0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0        S
887         1       1  female  19.0      0      0        S
888         0       3  female   NaN      1      2        S
889         1       1    male  26.0      0      0        C
890         0       3    male  32.0      0      0        Q

[889 rows x 7 columns]

In [585]:
x=a.iloc[:,1:]

In [586]:
x

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  26.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female   NaN      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[889 rows x 6 columns]

In [587]:
y=a.iloc[:,0:1]

In [588]:
y

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[889 rows x 1 columns]

In [589]:
from sklearn.model_selection import train_test_split

In [590]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)

In [591]:
xtrain

Pclass     Sex   Age  SibSp  Parch Embarked
364       3    male   NaN      1      0        Q
256       1  female   NaN      0      0        C
477       3    male  29.0      1      0        S
272       2  female  41.0      0      1        S
554       3  female  22.0      0      0        S
..      ...     ...   ...    ...    ...      ...
837       3    male   NaN      0      0        S
193       2    male   3.0      1      1        S
630       1    male  80.0      0      0        S
560       3    male   NaN      0      0        Q
685       2    male  25.0      1      2        C

[711 rows x 6 columns]

In [592]:
ytrain

Survived
364         0
256         1
477         0
272         1
554         1
..        ...
837         0
193         1
630         1
560         0
685         0

[711 rows x 1 columns]

In [593]:
xtest

Pclass     Sex   Age  SibSp  Parch Embarked
14        3  female  14.0      0      0        S
159       3    male   NaN      8      2        S
763       1  female  36.0      1      2        S
741       1    male  36.0      1      0        S
483       3  female  63.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
673       2    male  31.0      0      0        S
182       3    male   9.0      4      2        S
632       1    male  32.0      0      0        C
141       3  female  22.0      0      0        S

[178 rows x 6 columns]

In [594]:
ytest


Survived
14          0
159         0
763         1
741         0
483         1
..        ...
886         0
673         1
182         0
632         1
141         1

[178 rows x 1 columns]

In [595]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [596]:
tr=ColumnTransformer(
        transformers=[
            ('tr2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked']),
            ('tr3',SimpleImputer(),['Age'])
        ],remainder='passthrough')

In [597]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Sex', 'Embarked']),
                                ('tr3', SimpleImputer(), ['Age'])])

In [602]:
xtrain=tr.fit_transform(xtrain)
xtrain

array([[1., 1., 0., ..., 3., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 1., ..., 3., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 1., 0., ..., 3., 0., 0.],
       [1., 0., 0., ..., 2., 1., 2.]])

In [603]:
xtest=tr.fit_transform(xtest)
xtest

array([[0., 0., 1., ..., 3., 0., 0.],
       [1., 0., 1., ..., 3., 8., 2.],
       [0., 0., 1., ..., 1., 1., 2.],
       ...,
       [1., 0., 1., ..., 3., 4., 2.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 3., 0., 0.]])

In [604]:
from sklearn.linear_model import LogisticRegression

In [605]:
new=LogisticRegression( penalty='l2',
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    multi_class='auto',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)

In [607]:
new.fit(xtrain,ytrain)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [608]:
pred=new.predict(xtest)

In [609]:
pred

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1], dtype=int64)

In [610]:
ytest

Survived
14          0
159         0
763         1
741         0
483         1
..        ...
886         0
673         1
182         0
632         1
141         1

[178 rows x 1 columns]

In [611]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score

In [612]:
accuracy_score(ytest,pred)

0.7191011235955056

In [613]:
confusion_matrix(ytest,pred)

array([[84, 21],
       [29, 44]], dtype=int64)

In [614]:
precision_score(ytest,pred,average='micro')

0.7191011235955056

In [615]:
recall_score(ytest,pred,average='micro')

0.7191011235955056

In [616]:
f1_score(ytest,pred,average='micro')

0.7191011235955056